import { Product } from "./types";

// ── Categories ──
export const CATEGORIES = [
    { value: "bangles", label: "Bangles" },
    { value: "necklace", label: "Necklaces" },
    { value: "rings", label: "Rings" },
    { value: "earrings", label: "Earrings" },
    { value: "anklets", label: "Anklets" },
    { value: "bracelets", label: "Bracelets" },
];

export const MATERIALS = [
    { value: "kundan", label: "Kundan" },
    { value: "meenakari", label: "Meenakari" },
    { value: "velvet", label: "Velvet" },
    { value: "metal", label: "Metal" },
    { value: "stone", label: "Stone" },
    { value: "pearl", label: "Pearl" },
    { value: "beaded", label: "Beaded" },
    { value: "oxidised", label: "Oxidised" },
    { value: "lacquer", label: "Lacquer" },
];

export const OCCASIONS = [
    { value: "traditional", label: "Traditional" },
    { value: "bridal", label: "Bridal" },
    { value: "western", label: "Western" },
    { value: "festive", label: "Festive" },
    { value: "daily", label: "Daily Wear" },
    { value: "party", label: "Party Wear" },
    { value: "office", label: "Office Wear" },
];

export const PRICE_RANGES = [
    { value: "0-500", label: "Under ₹500", min: 0, max: 500 },
    { value: "500-1000", label: "₹500 - ₹1,000", min: 500, max: 1000 },
    { value: "1000-2000", label: "₹1,000 - ₹2,000", min: 1000, max: 2000 },
    { value: "2000-5000", label: "₹2,000 - ₹5,000", min: 2000, max: 5000 },
    { value: "5000+", label: "Above ₹5,000", min: 5000, max: 999999 },
];

export const SORT_OPTIONS = [
    { value: "newest", label: "Newest First" },
    { value: "price_asc", label: "Price: Low to High" },
    { value: "price_desc", label: "Price: High to Low" },
    { value: "discount", label: "Best Discount" },
    { value: "popular", label: "Most Popular" },
];

// ── Sample Products (mock data until backend is connected) ──
export const PRODUCTS: Product[] = [
    {
        _id: "1",
        name: "Royal Kundan Kada Set",
        description: "Exquisite kundan-studded kada set with intricate floral patterns. Handcrafted with premium quality stones set in a durable metal base. Perfect for weddings and festive occasions.",
        price: 1299,
        originalPrice: 2499,
        discount: 48,
        category: "bangles",
        material: "kundan",
        occasion: "bridal",
        weight: "85g",
        images: ["https://images.unsplash.com/photo-1515562141589-67f0d999b7f3?w=600&q=80&auto=format&fit=crop"],
        stock: 12,
        isFeatured: true,
        isActive: true,
        tags: ["bestseller", "kundan", "bridal"],
        createdAt: "2026-01-15",
    },
    {
        _id: "2",
        name: "Peacock Meenakari Bangle",
        description: "Vibrant peacock-inspired meenakari bangle with hand-painted enamel work in blues and greens. A celebration of traditional Rajasthani artistry.",
        price: 899,
        originalPrice: 1599,
        discount: 44,
        category: "bangles",
        material: "meenakari",
        occasion: "festive",
        weight: "60g",
        images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80&auto=format&fit=crop"],
        stock: 20,
        isFeatured: true,
        isActive: true,
        tags: ["new-arrival", "meenakari", "peacock"],
        createdAt: "2026-02-01",
    },
    {
        _id: "3",
        name: "Velvet Choker Necklace",
        description: "Elegant velvet choker with stone embellishments and adjustable tie-back. Adds a regal touch to any outfit.",
        price: 599,
        originalPrice: 999,
        discount: 40,
        category: "necklace",
        material: "velvet",
        occasion: "party",
        weight: "35g",
        images: ["https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&q=80&auto=format&fit=crop"],
        stock: 30,
        isFeatured: true,
        isActive: true,
        tags: ["trending", "velvet", "choker"],
        createdAt: "2026-02-05",
    },
    {
        _id: "4",
        name: "Oxidised Jhumka Earrings",
        description: "Statement oxidised silver jhumka earrings with bell detailing. Lightweight and comfortable for all-day wear.",
        price: 349,
        originalPrice: 699,
        discount: 50,
        category: "earrings",
        material: "oxidised",
        occasion: "traditional",
        weight: "25g",
        images: ["https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80&auto=format&fit=crop"],
        stock: 50,
        isFeatured: true,
        isActive: true,
        tags: ["bestseller", "oxidised", "jhumka"],
        createdAt: "2026-01-20",
    },
    {
        _id: "5",
        name: "Pearl Layered Necklace",
        description: "Multi-layered pearl necklace with adjustable clasp. Timeless elegance perfect for festive gatherings and formal events.",
        price: 799,
        originalPrice: 1499,
        discount: 47,
        category: "necklace",
        material: "pearl",
        occasion: "festive",
        weight: "45g",
        images: ["https://images.unsplash.com/photo-1515562141589-67f0d999b7f3?w=600&q=80&auto=format&fit=crop"],
        stock: 15,
        isFeatured: false,
        isActive: true,
        tags: ["pearl", "layered", "elegant"],
        createdAt: "2026-01-25",
    },
    {
        _id: "6",
        name: "Stone Studded Finger Ring",
        description: "Adjustable stone-studded ring with a large centre stone surrounded by tiny crystal accents. Fits all finger sizes.",
        price: 249,
        originalPrice: 499,
        discount: 50,
        category: "rings",
        material: "stone",
        occasion: "daily",
        weight: "10g",
        images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80&auto=format&fit=crop"],
        stock: 80,
        isFeatured: false,
        isActive: true,
        tags: ["adjustable", "stone", "daily"],
        createdAt: "2026-02-02",
    },
    {
        _id: "7",
        name: "Bridal Kundan Choker Set",
        description: "Grand bridal kundan choker set including necklace, earrings, and maang tikka. The ultimate bridal statement set with premium CZ stones.",
        price: 3499,
        originalPrice: 6999,
        discount: 50,
        category: "necklace",
        material: "kundan",
        occasion: "bridal",
        weight: "180g",
        images: ["https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&q=80&auto=format&fit=crop"],
        stock: 5,
        isFeatured: true,
        isActive: true,
        tags: ["bridal", "kundan", "set", "premium"],
        createdAt: "2026-02-10",
    },
    {
        _id: "8",
        name: "Metal Cuff Bracelet",
        description: "Bold geometric metal cuff bracelet with an antique gold finish. A modern, western-style accessory for the bold and confident.",
        price: 449,
        originalPrice: 799,
        discount: 44,
        category: "bracelets",
        material: "metal",
        occasion: "western",
        weight: "40g",
        images: ["https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80&auto=format&fit=crop"],
        stock: 25,
        isFeatured: false,
        isActive: true,
        tags: ["cuff", "metal", "western", "modern"],
        createdAt: "2026-02-08",
    },
    {
        _id: "9",
        name: "Beaded Anklet Pair",
        description: "Delicate beaded anklet pair with tiny bell charms. Adds a playful musical touch to your every step.",
        price: 199,
        originalPrice: 399,
        discount: 50,
        category: "anklets",
        material: "beaded",
        occasion: "daily",
        weight: "15g",
        images: ["https://images.unsplash.com/photo-1515562141589-67f0d999b7f3?w=600&q=80&auto=format&fit=crop"],
        stock: 60,
        isFeatured: false,
        isActive: true,
        tags: ["anklet", "beaded", "daily", "bells"],
        createdAt: "2026-01-28",
    },
    {
        _id: "10",
        name: "Lacquer Bangles Set of 12",
        description: "Traditional Rajasthani lacquer bangles set with stone work. Set of 12 beautifully colour-coordinated bangles for a complete look.",
        price: 499,
        originalPrice: 999,
        discount: 50,
        category: "bangles",
        material: "lacquer",
        occasion: "traditional",
        weight: "120g",
        images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80&auto=format&fit=crop"],
        stock: 35,
        isFeatured: true,
        isActive: true,
        tags: ["lacquer", "set", "rajasthani", "traditional"],
        createdAt: "2026-02-12",
    },
    {
        _id: "11",
        name: "Temple Motif Bangle Pair",
        description: "South Indian temple-inspired bangle pair with goddess and floral motifs in oxidised metal finish. Rich heritage design.",
        price: 699,
        originalPrice: 1299,
        discount: 46,
        category: "bangles",
        material: "metal",
        occasion: "traditional",
        weight: "70g",
        images: ["https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&q=80&auto=format&fit=crop"],
        stock: 18,
        isFeatured: false,
        isActive: true,
        tags: ["temple", "metal", "south-indian"],
        createdAt: "2026-02-06",
    },
    {
        _id: "12",
        name: "Western Charm Bracelet",
        description: "Trendy charm bracelet with dangling heart and star motifs. Adjustable chain with lobster clasp closure.",
        price: 349,
        originalPrice: 599,
        discount: 42,
        category: "bracelets",
        material: "metal",
        occasion: "western",
        weight: "20g",
        images: ["https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80&auto=format&fit=crop"],
        stock: 40,
        isFeatured: false,
        isActive: true,
        tags: ["charm", "western", "trendy"],
        createdAt: "2026-02-09",
    },
];
